### ISSUE TITLE
WebSocket inspector creator

### ISSUE THREAD

**Issue by laurakalbag** [statelyai/feedback#387]
### Details

Inspect frontend and/or backend applications remotely using Stately Inspector.

### Category

Devtools

**Comment by technoplato** [comment]
> ### Details
> 
> Inspect frontend and/or backend applications remotely using Stately Inspector.
> 
> ### Category
> 
> Devtools

@laurakalbag I think this is done?

![image](https://github.com/statelyai/feedback/assets/6922904/ac13d097-30cd-4934-bd80-b457f08f7fa0)

**Comment by laurakalbag** [comment]
> > ### Details
> > Inspect frontend and/or backend applications remotely using Stately Inspector.
> > ### Category
> > Devtools
> 
> @laurakalbag I think this is done?
> 
> ![image](https://private-user-images.githubusercontent.com/6922904/306306268-ac13d097-30cd-4934-bd80-b457f08f7fa0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA5OTksIm5iZiI6MTcwODQ0MDY5OSwicGF0aCI6Ii82OTIyOTA0LzMwNjMwNjI2OC1hYzEzZDA5Ny0zMGNkLTQ5MzQtYmQ4MC1iNDU3ZjA4ZjdmYTAuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ODgyZGNkZTQ2ZTYwYTM1OThlY2NmMTllOGYwMGNkNDU5M2E2MGMxODE1OWMzN2U3ZTkyOWQ3MTBlMDYxZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PdJCvW4Wdd-ARWSChEm3aw6B1FfG88ehiZv_FcpyzWs)

@technoplato Yes, thanks! Good catch!

**Comment by kkelk** [comment]
If this is done (awesome if so!), would it be possible to document usage somewhere? Currently it connects to `ws://localhost:8080`, so I assume there's a missing step somewhere (either pointing at the right url, or running some kind of local proxy?)

If the end result of this is that we can render multiple actors from different components in the same system (e.g. frontend and backend) together in one diagram, that'd be absolutely amazing :-)
