### ISSUE TITLE
GitHub/Figma and settings page display a 403 error message before loading

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/feedback#392]
### Details

Going to either of these urls will display a **403** error message about Premium subscription before loading the user's subscription.

GitHub: https://stately.ai/registry/user/my-settings?tab=GitHub
Figma: https://stately.ai/registry/user/my-settings?tab=Figma

https://github.com/statelyai/feedback/assets/12085950/1cc7d103-e385-44f9-8f49-d76342cb07b2

Note: Navigating to the settings tab works fine, but refreshing the page will show the error message.

### Category

Editor

**Comment by mellson** [comment]
Thanks for the feedback. We'll release a fix for this asap
