### ISSUE TITLE
onDone and onError transitions get lost after refresh

### ISSUE THREAD

**Issue by josephfh** [statelyai/feedback#395]
### Details

<img width="924" alt="image" src="https://github.com/statelyai/feedback/assets/889121/e951d678-9ef8-423a-8d17-1d09a56e1ba7">

I think this is not the case when I give the invoked actor an ID

### Category

Editor

**Comment by josephfh** [comment]
<img width="853" alt="image" src="https://github.com/statelyai/feedback/assets/889121/331a802f-f729-4aa1-84cd-6a0148a8c860">

I added an ID to this invoked actor and now I see the onDone and onError when it refreshes.

I assume the intended behaviour should be seeing 'done: anonymous' and 'error: anonymous' after reloading the editor

**Comment by kevinmaes** [comment]
Hi @josephfh! There was a bug with invoked actor `done` and `error` transitions disappearing for unnamed actor sources but this was fixed last week. Some machines during that period, like yours, have been affected. Very sorry for the inconvenience. Let us know if you continue to experience any problems though.
